### ISSUE TITLE
Add Scoreboard

### ISSUE THREAD

**Issue by Meyssam120** [Spordi/Pluginus1#54]
- [x] Gamename
- [x] Kills - Deaths
- [x] Level
- [x] Ranking

**Comment by Spordi** [comment]
Du stinkst nach thunfisch

 

Von: Meyssam <notifications@github.com> 
Gesendet: Samstag, 30. Mai 2020 13:33
An: Spordi/Pluginus1 <Pluginus1@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [Spordi/Pluginus1] Add Scoreboard (#54)

 

Closed #54 <https://github.com/Spordi/Pluginus1/issues/54> .
